;
; Manoonchai Keyboard Layout definition for Portable Keyboard Layout
;

[informations]
layoutname           = Manoonchai
layoutcode           = manoonchai
localeid             = 0000041E

copyright            = See Manoonchai project
company              = Manoonchai contributors
homepage             = https://github.com/narze/Manoonchai
version              = 0.3-portable

generated_at         = 2026-06-24
generated_from       = Manoonchai v0.3 README
modified_after_generate = yes


[global]
shiftstates = 0:1:6:7
img_width = 296
img_height = 102


[fingers]
row1 = 1123445567888
row2 = 1123445567888
row3 = 1123445567888
row4 = 11234455678


[layout]
;scan = VK	CapStat	0Norm	1Sh	6AGr	7AGrSh
SC002 = 1	0	1	!	๑	--	; QWERTY 1!
SC003 = 2	0	2	@	๒	--	; QWERTY 2@
SC004 = 3	0	3	#	๓	--	; QWERTY 3#
SC005 = 4	0	4	$	๔	--	; QWERTY 4$
SC006 = 5	0	5	%	๕	--	; QWERTY 5%
SC007 = 6	0	6	^	๖	--	; QWERTY 6^
SC008 = 7	0	7	&	๗	--	; QWERTY 7&
SC009 = 8	0	8	*	๘	--	; QWERTY 8*
SC00a = 9	0	9	(	๙	--	; QWERTY 9(
SC00b = 0	0	0	)	๐	--	; QWERTY 0)
SC00c = OEM_MINUS	0	-	_	÷	--	; QWERTY -_
SC00d = OEM_PLUS	0	=	+	×	--	; QWERTY =+

SC010 = Q	0	ใ	ฒ	--	--	; QWERTY qQ
SC011 = W	0	ต	ฏ	--	--	; QWERTY wW
SC012 = E	0	ห	ซ	--	--	; QWERTY eE
SC013 = R	0	ล	ญ	--	--	; QWERTY rR
SC014 = T	0	ส	ฟ	--	--	; QWERTY tT
SC015 = Y	0	ป	ฉ	--	--	; QWERTY yY
SC016 = U	0	ั	ึ	ฺ	--	; QWERTY uU
SC017 = I	0	ก	ธ	--	--	; QWERTY iI
SC018 = O	0	ิ	ฐ	--	--	; QWERTY oO
SC019 = P	0	บ	ฎ	--	--	; QWERTY pP
SC01a = OEM_4	0	็	ฆ	[	{	; QWERTY [{
SC01b = OEM_6	0	ฬ	ฑ	]	}	; QWERTY ]}
SC02b = OEM_5	0	ฯ	ฌ	\	|	; QWERTY \|

SC01e = A	0	ง	ษ	◌	--	; QWERTY aA
SC01f = S	0	เ	ถ	๏	--	; QWERTY sS
SC020 = D	0	ร	แ	๛	--	; QWERTY dD
SC021 = F	0	น	ช	฿	--	; QWERTY fF
SC022 = G	0	ม	พ	--	--	; QWERTY gG
SC023 = H	0	อ	ผ	ํ	--	; QWERTY hH
SC024 = J	0	า	ำ	ๅ	--	; QWERTY jJ
SC025 = K	0	่	ข	ฃ	--	; QWERTY kK
SC026 = L	0	้	โ	--	--	; QWERTY lL
SC027 = OEM_1	0	ว	ภ	;	:	; QWERTY ;:
SC028 = OEM_7	0	ื	"	'	"	; QWERTY '"

SC02c = Z	0	ุ	ฤ	ฦ	--	; QWERTY zZ
SC02d = X	0	ไ	ฝ	--	--	; QWERTY xX
SC02e = C	0	ท	ๆ	๚	--	; QWERTY cC
SC02f = V	0	ย	ณ	--	--	; QWERTY vV
SC030 = B	0	จ	๊	--	--	; QWERTY bB
SC031 = N	0	ค	๋	ฅ	--	; QWERTY nN
SC032 = M	0	ี	์	๎	--	; QWERTY mM
SC033 = OEM_COMMA	0	ด	ศ	,	<	; QWERTY ,<
SC034 = OEM_PERIOD	0	ะ	ฮ	.	>	; QWERTY .>
SC035 = OEM_2	0	ู	?	/	?	; QWERTY /?

SC039 = SPACE	0	={space}	={space}	={space}	={space}	; QWERTY Space
SC053 = DECIMAL	0	.	.	.	.	; QWERTY Decimal in Numpad

